from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1135, 921)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExitButton.sizePolicy().hasHeightForWidth())
        self.ExitButton.setSizePolicy(sizePolicy)
        self.ExitButton.setMaximumSize(QtCore.QSize(38, 34))
        self.ExitButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ExitButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ExitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/exit.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExitButton.setIcon(icon)
        self.ExitButton.setIconSize(QtCore.QSize(25, 25))
        self.ExitButton.setFlat(True)
        self.ExitButton.setObjectName("ExitButton")
        self.horizontalLayout_2.addWidget(self.ExitButton)
        self.play = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play.sizePolicy().hasHeightForWidth())
        self.play.setSizePolicy(sizePolicy)
        self.play.setMaximumSize(QtCore.QSize(38, 34))
        self.play.setAutoFillBackground(False)
        self.play.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon1)
        self.play.setIconSize(QtCore.QSize(25, 25))
        self.play.setDefault(False)
        self.play.setFlat(True)
        self.play.setObjectName("play")
        self.horizontalLayout_2.addWidget(self.play)
        self.pause = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause.sizePolicy().hasHeightForWidth())
        self.pause.setSizePolicy(sizePolicy)
        self.pause.setMaximumSize(QtCore.QSize(38, 34))
        self.pause.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon2)
        self.pause.setIconSize(QtCore.QSize(25, 25))
        self.pause.setFlat(True)
        self.pause.setObjectName("pause")
        self.horizontalLayout_2.addWidget(self.pause)
        self.zoom_in = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_in.sizePolicy().hasHeightForWidth())
        self.zoom_in.setSizePolicy(sizePolicy)
        self.zoom_in.setMaximumSize(QtCore.QSize(43, 39))
        self.zoom_in.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/zoomin.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_in.setIcon(icon3)
        self.zoom_in.setIconSize(QtCore.QSize(30, 30))
        self.zoom_in.setFlat(True)
        self.zoom_in.setObjectName("zoom_in")
        self.horizontalLayout_2.addWidget(self.zoom_in)
        self.zoom_out = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_out.sizePolicy().hasHeightForWidth())
        self.zoom_out.setSizePolicy(sizePolicy)
        self.zoom_out.setMaximumSize(QtCore.QSize(43, 39))
        self.zoom_out.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/zoom out.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_out.setIcon(icon4)
        self.zoom_out.setIconSize(QtCore.QSize(30, 30))
        self.zoom_out.setFlat(True)
        self.zoom_out.setObjectName("zoom_out")
        self.horizontalLayout_2.addWidget(self.zoom_out)
        self.zoomx = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomx.sizePolicy().hasHeightForWidth())
        self.zoomx.setSizePolicy(sizePolicy)
        self.zoomx.setMaximumSize(QtCore.QSize(43, 39))
        self.zoomx.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/zoom x.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomx.setIcon(icon5)
        self.zoomx.setIconSize(QtCore.QSize(30, 30))
        self.zoomx.setFlat(True)
        self.zoomx.setObjectName("zoomx")
        self.horizontalLayout_2.addWidget(self.zoomx)
        self.zoomy = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomy.sizePolicy().hasHeightForWidth())
        self.zoomy.setSizePolicy(sizePolicy)
        self.zoomy.setMaximumSize(QtCore.QSize(43, 39))
        self.zoomy.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/zoom y.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomy.setIcon(icon6)
        self.zoomy.setIconSize(QtCore.QSize(30, 30))
        self.zoomy.setFlat(True)
        self.zoomy.setObjectName("zoomy")
        self.horizontalLayout_2.addWidget(self.zoomy)
        self.clear_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_Button.sizePolicy().hasHeightForWidth())
        self.clear_Button.setSizePolicy(sizePolicy)
        self.clear_Button.setMaximumSize(QtCore.QSize(38, 34))
        self.clear_Button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/delete-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_Button.setIcon(icon7)
        self.clear_Button.setIconSize(QtCore.QSize(25, 25))
        self.clear_Button.setFlat(True)
        self.clear_Button.setObjectName("clear_Button")
        self.horizontalLayout_2.addWidget(self.clear_Button)
        self.Export = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Export.sizePolicy().hasHeightForWidth())
        self.Export.setSizePolicy(sizePolicy)
        self.Export.setMaximumSize(QtCore.QSize(38, 34))
        self.Export.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/pdf-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Export.setIcon(icon8)
        self.Export.setIconSize(QtCore.QSize(25, 25))
        self.Export.setFlat(True)
        self.Export.setObjectName("Export")
        self.horizontalLayout_2.addWidget(self.Export)
        self.scroll_x = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_x.sizePolicy().hasHeightForWidth())
        self.scroll_x.setSizePolicy(sizePolicy)
        self.scroll_x.setMaximumSize(QtCore.QSize(84, 22))
        self.scroll_x.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scroll_x.setOrientation(QtCore.Qt.Horizontal)
        self.scroll_x.setObjectName("scroll_x")
        self.horizontalLayout_2.addWidget(self.scroll_x)
        self.scroll_y = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_y.sizePolicy().hasHeightForWidth())
        self.scroll_y.setSizePolicy(sizePolicy)
        self.scroll_y.setMaximumSize(QtCore.QSize(84, 22))
        self.scroll_y.setOrientation(QtCore.Qt.Horizontal)
        self.scroll_y.setObjectName("scroll_y")
        self.horizontalLayout_2.addWidget(self.scroll_y)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMaximumSize(QtCore.QSize(73, 22))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(398, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radiobutton1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radiobutton1.setText("")
        self.radiobutton1.setObjectName("r1")
        self.radiobutton1.value=1
        self.verticalLayout_2.addWidget(self.radiobutton1)
        self.label_Channel1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Channel1.setFont(font)
        self.label_Channel1.setObjectName("label_Channel1")
        self.verticalLayout_2.addWidget(self.label_Channel1)
        self.input_graph = PlotWidget(self.centralwidget)
        self.input_graph.setObjectName("Channel_1")
        self.verticalLayout_2.addWidget(self.input_graph)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.equalizer_slider1 = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equalizer_slider1.sizePolicy().hasHeightForWidth())
        self.equalizer_slider1.setSizePolicy(sizePolicy)
        self.equalizer_slider1.setMaximumSize(QtCore.QSize(22, 160))
        self.equalizer_slider1.setMaximum(10)
        self.equalizer_slider1.setPageStep(1)
        self.equalizer_slider1.setProperty("value", 1)
        self.equalizer_slider1.setOrientation(QtCore.Qt.Vertical)
        self.equalizer_slider1.setObjectName("slider_1")
        self.gridLayout_2.addWidget(self.equalizer_slider1, 0, 0, 1, 1)
        self.equalizer_slider2 = QtWidgets.QSlider(self.centralwidget)
        self.equalizer_slider2.setMaximumSize(QtCore.QSize(22, 160))
        self.equalizer_slider2.setMaximum(10)
        self.equalizer_slider2.setPageStep(1)
        self.equalizer_slider2.setProperty("value", 1)
        self.equalizer_slider2.setOrientation(QtCore.Qt.Vertical)
        self.equalizer_slider2.setObjectName("slider_2")
        self.gridLayout_2.addWidget(self.equalizer_slider2, 0, 1, 1, 1)
        self.equalizer_slider3 = QtWidgets.QSlider(self.centralwidget)
        self.equalizer_slider3.setMaximumSize(QtCore.QSize(22, 160))
        self.equalizer_slider3.setMaximum(10)
        self.equalizer_slider3.setPageStep(1)
        self.equalizer_slider3.setProperty("value", 1)
        self.equalizer_slider3.setOrientation(QtCore.Qt.Vertical)
        self.equalizer_slider3.setObjectName("slider_3")
        self.gridLayout_2.addWidget(self.equalizer_slider3, 0, 2, 1, 1)
        self.equalizer_slider4 = QtWidgets.QSlider(self.centralwidget)
        self.equalizer_slider4.setMaximumSize(QtCore.QSize(22, 160))
        self.equalizer_slider4.setMaximum(10)
        self.equalizer_slider4.setPageStep(1)
        self.equalizer_slider4.setProperty("value", 1)
        self.equalizer_slider4.setOrientation(QtCore.Qt.Vertical)
        self.equalizer_slider4.setObjectName("slider_4")
        self.gridLayout_2.addWidget(self.equalizer_slider4, 0, 3, 1, 1)
        self.equalizer_slider5 = QtWidgets.QSlider(self.centralwidget)
        self.equalizer_slider5.setMaximumSize(QtCore.QSize(22, 160))
        self.equalizer_slider5.setMaximum(10)
        self.equalizer_slider5.setPageStep(1)
        self.equalizer_slider5.setProperty("value", 1)
        self.equalizer_slider5.setOrientation(QtCore.Qt.Vertical)
        self.equalizer_slider5.setObjectName("slider_5")
        self.gridLayout_2.addWidget(self.equalizer_slider5, 0, 4, 1, 1)
        self.equalizer_slider6 = QtWidgets.QSlider(self.centralwidget)
        self.equalizer_slider6.setMaximumSize(QtCore.QSize(22, 160))
        self.equalizer_slider6.setMaximum(10)
        self.equalizer_slider6.setPageStep(1)
        self.equalizer_slider6.setProperty("value", 1)
        self.equalizer_slider6.setOrientation(QtCore.Qt.Vertical)
        self.equalizer_slider6.setObjectName("slider_6")
        self.gridLayout_2.addWidget(self.equalizer_slider6, 0, 5, 1, 1)
        self.equalizer_slider7 = QtWidgets.QSlider(self.centralwidget)
        self.equalizer_slider7.setMaximumSize(QtCore.QSize(22, 160))
        self.equalizer_slider7.setMaximum(10)
        self.equalizer_slider7.setPageStep(1)
        self.equalizer_slider7.setProperty("value", 1)
        self.equalizer_slider7.setOrientation(QtCore.Qt.Vertical)
        self.equalizer_slider7.setObjectName("slider_7")
        self.gridLayout_2.addWidget(self.equalizer_slider7, 0, 6, 1, 1)
        self.equalizer_slider8 = QtWidgets.QSlider(self.centralwidget)
        self.equalizer_slider8.setMaximumSize(QtCore.QSize(22, 160))
        self.equalizer_slider8.setMaximum(10)
        self.equalizer_slider8.setPageStep(1)
        self.equalizer_slider8.setProperty("value", 1)
        self.equalizer_slider8.setOrientation(QtCore.Qt.Vertical)
        self.equalizer_slider8.setObjectName("slider_8")
        self.gridLayout_2.addWidget(self.equalizer_slider8, 0, 7, 1, 1)
        self.equalizer_slider9 = QtWidgets.QSlider(self.centralwidget)
        self.equalizer_slider9.setMaximumSize(QtCore.QSize(22, 160))
        self.equalizer_slider9.setMaximum(10)
        self.equalizer_slider9.setPageStep(1)
        self.equalizer_slider9.setProperty("value", 1)
        self.equalizer_slider9.setOrientation(QtCore.Qt.Vertical)
        self.equalizer_slider9.setObjectName("slider_9")
        self.gridLayout_2.addWidget(self.equalizer_slider9, 0, 8, 1, 1)
        self.equalizer_slider10 = QtWidgets.QSlider(self.centralwidget)
        self.equalizer_slider10.setMaximumSize(QtCore.QSize(21, 160))
        self.equalizer_slider10.setMaximum(10)
        self.equalizer_slider10.setPageStep(1)
        self.equalizer_slider10.setProperty("value", 1)
        self.equalizer_slider10.setOrientation(QtCore.Qt.Vertical)
        self.equalizer_slider10.setObjectName("slider_10")
        self.gridLayout_2.addWidget(self.equalizer_slider10, 0, 9, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMaximumSize(QtCore.QSize(41, 23))
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 1.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_2.addWidget(self.lcdNumber, 1, 0, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setMaximumSize(QtCore.QSize(41, 23))
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setProperty("value", 1.0)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout_2.addWidget(self.lcdNumber_2, 1, 1, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setMaximumSize(QtCore.QSize(41, 23))
        self.lcdNumber_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_3.setProperty("value", 1.0)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout_2.addWidget(self.lcdNumber_3, 1, 2, 1, 1)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setMaximumSize(QtCore.QSize(41, 23))
        self.lcdNumber_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_4.setProperty("value", 1.0)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.gridLayout_2.addWidget(self.lcdNumber_4, 1, 3, 1, 1)
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setMaximumSize(QtCore.QSize(41, 23))
        self.lcdNumber_5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_5.setProperty("value", 1.0)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.gridLayout_2.addWidget(self.lcdNumber_5, 1, 4, 1, 1)
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setMaximumSize(QtCore.QSize(41, 23))
        self.lcdNumber_6.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_6.setProperty("value", 1.0)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.gridLayout_2.addWidget(self.lcdNumber_6, 1, 5, 1, 1)
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_7.setMaximumSize(QtCore.QSize(41, 23))
        self.lcdNumber_7.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_7.setProperty("value", 1.0)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.gridLayout_2.addWidget(self.lcdNumber_7, 1, 6, 1, 1)
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_8.setMaximumSize(QtCore.QSize(41, 23))
        self.lcdNumber_8.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_8.setProperty("value", 1.0)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.gridLayout_2.addWidget(self.lcdNumber_8, 1, 7, 1, 1)
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_9.setMaximumSize(QtCore.QSize(41, 23))
        self.lcdNumber_9.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_9.setProperty("value", 1.0)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.gridLayout_2.addWidget(self.lcdNumber_9, 1, 8, 1, 1)
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_10.setMaximumSize(QtCore.QSize(41, 23))
        self.lcdNumber_10.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_10.setProperty("value", 1.0)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.gridLayout_2.addWidget(self.lcdNumber_10, 1, 9, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.radiobutton2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radiobutton2.setText("")
        self.radiobutton2.setObjectName("r2")
        self.radiobutton2.value=2
        self.verticalLayout_2.addWidget(self.radiobutton2)
        self.label_Channel2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Channel2.setFont(font)
        self.label_Channel2.setObjectName("label_Channel2")
        self.verticalLayout_2.addWidget(self.label_Channel2)
        self.output_graph = PlotWidget(self.centralwidget)
        self.output_graph.setObjectName("Channel_2")
        self.verticalLayout_2.addWidget(self.output_graph)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radiobutton3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radiobutton3.setText("")
        self.radiobutton3.setObjectName("r3")
        self.radiobutton3.value=3
        self.verticalLayout.addWidget(self.radiobutton3)
        self.label_Spectrogram_1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Spectrogram_1.setFont(font)
        self.label_Spectrogram_1.setObjectName("label_Spectrogram_1")
        self.verticalLayout.addWidget(self.label_Spectrogram_1)
        self.Spectrogram_input = pg.GraphicsLayoutWidget(self.centralwidget)
        self.Spectrogram_input.setObjectName("Spectrogram_1")
        self.verticalLayout.addWidget(self.Spectrogram_input)
        self.radiobutton4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radiobutton4.setText("")
        self.radiobutton4.setObjectName("r4")
        self.radiobutton4.value=4
        self.verticalLayout.addWidget(self.radiobutton4)
        self.label_Spectrogram_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Spectrogram_2.setFont(font)
        self.label_Spectrogram_2.setObjectName("label_Spectrogram_2")
        self.verticalLayout.addWidget(self.label_Spectrogram_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Spectrogram_output = pg.GraphicsLayoutWidget(self.centralwidget)
        self.Spectrogram_output.setObjectName("Spectrogram_2")
        self.gridLayout.addWidget(self.Spectrogram_output, 0, 0, 2, 1)
        self.maxfrequency_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxfrequency_slider.sizePolicy().hasHeightForWidth())
        self.maxfrequency_slider.setSizePolicy(sizePolicy)
        self.maxfrequency_slider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.maxfrequency_slider.setMaximum(3)
        self.maxfrequency_slider.setPageStep(1)
        self.maxfrequency_slider.setOrientation(QtCore.Qt.Vertical)
        self.maxfrequency_slider.setInvertedAppearance(True)
        self.maxfrequency_slider.setInvertedControls(True)
        self.maxfrequency_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.maxfrequency_slider.setObjectName("slider_13")
        self.gridLayout.addWidget(self.maxfrequency_slider, 0, 1, 1, 1)
        self.minfrequency_slider = QtWidgets.QSlider(self.centralwidget)
        self.minfrequency_slider.setMaximum(3)
        self.minfrequency_slider.setPageStep(1)
        self.minfrequency_slider.setOrientation(QtCore.Qt.Vertical)
        self.minfrequency_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.minfrequency_slider.setObjectName("slider_14")
        self.gridLayout.addWidget(self.minfrequency_slider, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1135, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Play_Signal_1 = QtWidgets.QAction(MainWindow)
        self.Play_Signal_1.setObjectName("Play_Signal_1")
        self.Pause_Signal_1 = QtWidgets.QAction(MainWindow)
        self.Pause_Signal_1.setObjectName("Pause_Signal_1")
        self.Clear_Signal_1 = QtWidgets.QAction(MainWindow)
        self.Clear_Signal_1.setObjectName("Clear_Signal_1")
        self.Play_Signal_2 = QtWidgets.QAction(MainWindow)
        self.Play_Signal_2.setObjectName("Play_Signal_2")
        self.Pause_Signal_2 = QtWidgets.QAction(MainWindow)
        self.Pause_Signal_2.setObjectName("Pause_Signal_2")
        self.Clear_Signal_2 = QtWidgets.QAction(MainWindow)
        self.Clear_Signal_2.setObjectName("Clear_Signal_2")
        self.Play_Signal_3 = QtWidgets.QAction(MainWindow)
        self.Play_Signal_3.setObjectName("Play_Signal_3")
        self.Pause_Signal_3 = QtWidgets.QAction(MainWindow)
        self.Pause_Signal_3.setObjectName("Pause_Signal_3")
        self.Clear_Signal_3 = QtWidgets.QAction(MainWindow)
        self.Clear_Signal_3.setObjectName("Clear_Signal_3")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_2 = QtWidgets.QAction(MainWindow)
        self.actionOpen_2.setObjectName("actionOpen_2")
        self.actionOpen_3 = QtWidgets.QAction(MainWindow)
        self.actionOpen_3.setObjectName("actionOpen_3")
        self.OpenChannel_1 = QtWidgets.QAction(MainWindow)
        self.OpenChannel_1.setObjectName("OpenChannel_1")
        self.OpenChannel_2 = QtWidgets.QAction(MainWindow)
        self.OpenChannel_2.setObjectName("OpenChannel_2")
        self.OpenChannel_3 = QtWidgets.QAction(MainWindow)
        self.OpenChannel_3.setObjectName("OpenChannel_3")
        self.zoom_x_Signal_1 = QtWidgets.QAction(MainWindow)
        self.zoom_x_Signal_1.setObjectName("zoom_x_Signal_1")
        self.zoom_x_Signal_2 = QtWidgets.QAction(MainWindow)
        self.zoom_x_Signal_2.setObjectName("zoom_x_Signal_2")
        self.zoom_x_Signal_3 = QtWidgets.QAction(MainWindow)
        self.zoom_x_Signal_3.setObjectName("zoom_x_Signal_3")
        self.zoom_y_Signal_1 = QtWidgets.QAction(MainWindow)
        self.zoom_y_Signal_1.setObjectName("zoom_y_Signal_1")
        self.zoom_y_Signal_2 = QtWidgets.QAction(MainWindow)
        self.zoom_y_Signal_2.setObjectName("zoom_y_Signal_2")
        self.zoom_y_Signal_3 = QtWidgets.QAction(MainWindow)
        self.zoom_y_Signal_3.setObjectName("zoom_y_Signal_3")
        self.Export_Signal_1 = QtWidgets.QAction(MainWindow)
        self.Export_Signal_1.setObjectName("Export_Signal_1")
        self.Export_Signal_2 = QtWidgets.QAction(MainWindow)
        self.Export_Signal_2.setObjectName("Export_Signal_2")
        self.Export_Signal_3 = QtWidgets.QAction(MainWindow)
        self.Export_Signal_3.setObjectName("Export_Signal_3")
        self.original_Spectrogram = QtWidgets.QAction(MainWindow)
        self.original_Spectrogram.setObjectName("original_Spectrogram")
        self.Signal_2_Spectrogram = QtWidgets.QAction(MainWindow)
        self.Signal_2_Spectrogram.setObjectName("Signal_2_Spectrogram")
        self.Signal_3_Spectrogram = QtWidgets.QAction(MainWindow)
        self.Signal_3_Spectrogram.setObjectName("Signal_3_Spectrogram")
        self.actionZoom_In = QtWidgets.QAction(MainWindow)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionZoom_X = QtWidgets.QAction(MainWindow)
        self.actionZoom_X.setObjectName("actionZoom_X")
        self.actionZoom_Y = QtWidgets.QAction(MainWindow)
        self.actionZoom_Y.setObjectName("actionZoom_Y")
        self.actionopen_file = QtWidgets.QAction(MainWindow)
        self.actionopen_file.setObjectName("actionopen_file")
        self.actionnew_window = QtWidgets.QAction(MainWindow)
        self.actionnew_window.setObjectName("actionnew_window")
        self.menuFile.addAction(self.actionopen_file)
        self.menuFile.addAction(self.actionnew_window)
        self.menuView.addAction(self.actionZoom_In)
        self.menuView.addAction(self.actionZoom_Out)
        self.menuView.addAction(self.actionZoom_X)
        self.menuView.addAction(self.actionZoom_Y)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.equalizer_slider1.valueChanged['int'].connect(self.lcdNumber.display)
        self.equalizer_slider2.valueChanged['int'].connect(self.lcdNumber_2.display)
        self.equalizer_slider3.valueChanged['int'].connect(self.lcdNumber_3.display)
        self.equalizer_slider4.valueChanged['int'].connect(self.lcdNumber_4.display)
        self.equalizer_slider5.valueChanged['int'].connect(self.lcdNumber_5.display)
        self.equalizer_slider6.valueChanged['int'].connect(self.lcdNumber_6.display)
        self.equalizer_slider7.valueChanged['int'].connect(self.lcdNumber_7.display)
        self.equalizer_slider8.valueChanged['int'].connect(self.lcdNumber_8.display)
        self.equalizer_slider9.valueChanged['int'].connect(self.lcdNumber_9.display)
        self.equalizer_slider10.valueChanged['int'].connect(self.lcdNumber_10.display)

        self.scroll_y.hide()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ExitButton.setToolTip(_translate("MainWindow", "exit"))
        self.ExitButton.setShortcut(_translate("MainWindow", "Esc"))
        self.play.setToolTip(_translate("MainWindow", "play"))
        self.play.setShortcut(_translate("MainWindow", "P"))
        self.pause.setToolTip(_translate("MainWindow", "pause"))
        self.pause.setShortcut(_translate("MainWindow", "S"))
        self.zoom_in.setToolTip(_translate("MainWindow", "zoom in "))
        self.zoom_in.setShortcut(_translate("MainWindow", "+"))
        self.zoom_out.setToolTip(_translate("MainWindow", "zoom out"))
        self.zoom_out.setShortcut(_translate("MainWindow", "-"))
        self.zoomx.setToolTip(_translate("MainWindow", "zoom x"))
        self.zoomx.setShortcut(_translate("MainWindow", "X"))
        self.zoomy.setToolTip(_translate("MainWindow", "zoom y"))
        self.zoomy.setShortcut(_translate("MainWindow", "Y"))
        self.clear_Button.setToolTip(_translate("MainWindow", "clear"))
        self.clear_Button.setShortcut(_translate("MainWindow", "Backspace"))
        self.Export.setToolTip(_translate("MainWindow", "export as pdf"))
        self.Export.setShortcut(_translate("MainWindow", "E"))
        self.scroll_x.setToolTip(_translate("MainWindow", "scroll x"))
        self.scroll_y.setToolTip(_translate("MainWindow", "scroll y"))
        self.radiobutton1.setShortcut(_translate("MainWindow", "1"))
        self.label_Channel1.setText(_translate("MainWindow", "Original Signal"))
        self.radiobutton2.setShortcut(_translate("MainWindow", "2"))
        self.label_Channel2.setText(_translate("MainWindow", "Modified Signal"))
        self.radiobutton3.setShortcut(_translate("MainWindow", "1"))
        self.label_Spectrogram_1.setText(_translate("MainWindow", "Original Spectrogram"))
        self.radiobutton4.setShortcut(_translate("MainWindow", "1"))
        self.label_Spectrogram_2.setText(_translate("MainWindow", "Modified Spectogram"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.Play_Signal_1.setText(_translate("MainWindow", "Play"))
        self.Pause_Signal_1.setText(_translate("MainWindow", "Pause"))
        self.Clear_Signal_1.setText(_translate("MainWindow", "Clear"))
        self.Play_Signal_2.setText(_translate("MainWindow", "Play"))
        self.Pause_Signal_2.setText(_translate("MainWindow", "Pause"))
        self.Clear_Signal_2.setText(_translate("MainWindow", "Clear"))
        self.Play_Signal_3.setText(_translate("MainWindow", "Play"))
        self.Pause_Signal_3.setText(_translate("MainWindow", "Pause"))
        self.Clear_Signal_3.setText(_translate("MainWindow", "Clear"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen_2.setText(_translate("MainWindow", "Open"))
        self.actionOpen_3.setText(_translate("MainWindow", "Open"))
        self.OpenChannel_1.setText(_translate("MainWindow", "Channel 1"))
        self.OpenChannel_1.setShortcut(_translate("MainWindow", "O, 1"))
        self.OpenChannel_2.setText(_translate("MainWindow", "Channel 2"))
        self.OpenChannel_2.setShortcut(_translate("MainWindow", "O, 2"))
        self.OpenChannel_3.setText(_translate("MainWindow", "Channel 3"))
        self.OpenChannel_3.setShortcut(_translate("MainWindow", "O, 3"))
        self.zoom_x_Signal_1.setText(_translate("MainWindow", "Signal 1"))
        self.zoom_x_Signal_2.setText(_translate("MainWindow", "Signal 2"))
        self.zoom_x_Signal_3.setText(_translate("MainWindow", "Signal 3"))
        self.zoom_y_Signal_1.setText(_translate("MainWindow", "Signal 1"))
        self.zoom_y_Signal_2.setText(_translate("MainWindow", "Signal 2"))
        self.zoom_y_Signal_3.setText(_translate("MainWindow", "Signal 3"))
        self.Export_Signal_1.setText(_translate("MainWindow", "Export Signal 1"))
        self.Export_Signal_2.setText(_translate("MainWindow", "Export Signal 2"))
        self.Export_Signal_3.setText(_translate("MainWindow", "Export Signal 3"))
        self.original_Spectrogram.setText(_translate("MainWindow", "Signal 1 Spectrogram"))
        self.original_Spectrogram.setShortcut(_translate("MainWindow", "G, 1"))
        self.Signal_2_Spectrogram.setText(_translate("MainWindow", "Signal 2 Spectrogram"))
        self.Signal_2_Spectrogram.setShortcut(_translate("MainWindow", "G, 2"))
        self.Signal_3_Spectrogram.setText(_translate("MainWindow", "Signal 3 Spectrogram"))
        self.Signal_3_Spectrogram.setShortcut(_translate("MainWindow", "G, 3"))
        self.actionZoom_In.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoom_X.setText(_translate("MainWindow", "Zoom X"))
        self.actionZoom_Y.setText(_translate("MainWindow", "Zoom Y"))
        self.actionopen_file.setText(_translate("MainWindow", "open file"))
        self.actionnew_window.setText(_translate("MainWindow", "new window"))
        self.comboBox.setItemText(0, _translate("MainWindow", "thermal"))
        self.comboBox.setItemText(1, _translate("MainWindow", "flame"))
        self.comboBox.setItemText(2, _translate("MainWindow", "yellowy"))
        self.comboBox.setItemText(3, _translate("MainWindow", "bipolar"))
        self.comboBox.setItemText(4, _translate("MainWindow", "spectrum"))
        self.comboBox.setItemText(5, _translate("MainWindow", "cyclic"))
        self.comboBox.setItemText(6, _translate("MainWindow", "greyclip"))
        self.comboBox.setItemText(7, _translate("MainWindow", "grey"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
